#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# Multi monitor support
xrandr --output DisplayPort-0 --mode 1920x1080 --rate 120 --left-of DisplayPort-2 --output DisplayPort-2 --mode 1920x1080 --rate 120 &
bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor DisplayPort-2 -d VI VII VIII IX X

# Autostart
nitrogen --restore & # Set wallpaper
polybar mybar &	     # Start a bar
picom &		     # Compositor

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
